# Copyright 2024 The Sigstore Authors
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.repository == 'sigstore/sigstore-devops-tools'

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.22'
          check-latest: true

      - name: build get-oncall
        run: go build -o get-oncall ./cmd/get_oncall
