# Copyright 2024 The Sigstore Authors
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.repository == 'sigstore/sigstore-devops-tools'

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: './go.mod'
          check-latest: true

      - name: build get-oncall
        run: go build -o get-oncall ./cmd/get_oncall
