name: deploy-get-oncall

on:
  push:
    branches:
      - main
    paths:
      - "get-oncall/**"
      - ".github/workflows/deploy-function-getoncall.yaml"
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - id: auth
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # v1.0.0
        with:
          workload_identity_provider: "projects/801815070094/locations/global/workloadIdentityPools/tooling-pool/providers/github-actions-provider"
          service_account: "github-actions@sigstore-support-tooling.iam.gserviceaccount.com"

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@14509ca55199d9348161571e36c48e44f855030d # v1.0.0
        with:
          name: 'GetOncall'
          runtime: 'go116'
          entry_point: 'GetOncall'
          project_id: ${{ env.GCP_PROJECT }}
          source_dir: ./get-oncall
          secret_environment_variables: 'SLACK_SECRET=projects/${{ env.GCP_PROJECT }}/secrets/SLACK_CLIENT_SECRET/versions/,SLACK_API_KEY=projects/${{ env.GCP_PROJECT }}/secrets/SLACK_API_KEY/versions/,PD_API_KEY=projects/${{ env.GCP_PROJECT }}/secrets/PD_API_KEY/versions/'
          memory_mb: '512'
          region: us-central1
          min_instances: 0
          max_instances: 1
          timeout: 60
          deploy_timeout: 900
