name: deploy-get-oncall

on:
  push:
    branches:
      - main
    paths:
      - "get-oncall/**"
      - ".github/workflows/deploy-function-getoncall.yaml"
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - id: auth
        uses: google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa # v2.1.3
        with:
          workload_identity_provider: "projects/801815070094/locations/global/workloadIdentityPools/tooling-pool/providers/github-actions-provider"
          service_account: "github-actions@sigstore-support-tooling.iam.gserviceaccount.com"

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@b418957976ca9302f13bf31bd06aa0256b8263e1 # v2.1.0
        with:
          name: 'GetOncall'
          runtime: 'go121'
          entry_point: 'GetOncall'
          project_id: ${{ env.GCP_PROJECT }}
          source_dir: ./get-oncall
          secret_environment_variables: 'SLACK_SECRET=projects/${{ env.GCP_PROJECT }}/secrets/SLACK_CLIENT_SECRET/versions/,SLACK_API_KEY=projects/${{ env.GCP_PROJECT }}/secrets/SLACK_API_KEY/versions/,PD_API_KEY=projects/${{ env.GCP_PROJECT }}/secrets/PD_API_KEY/versions/'
          memory_mb: '512'
          region: us-central1
          min_instances: 0
          max_instances: 1
          timeout: 60
          deploy_timeout: 900
