name: deploy-get-oncall

on:
  push:
    branches:
      - main
    paths:
      - "get-oncall/**"
      - ".github/workflows/deploy-function-getoncall.yaml"
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - id: auth
        uses: google-github-actions/auth@f6de81663f7788d05bd15bcce18f0e57f23f0846 # v2.0.1
        with:
          workload_identity_provider: "projects/801815070094/locations/global/workloadIdentityPools/tooling-pool/providers/github-actions-provider"
          service_account: "github-actions@sigstore-support-tooling.iam.gserviceaccount.com"

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@d8c8efb902ce8702540e8ae3a4d01a5f719c9c30 # v2.0.0
        with:
          name: 'GetOncall'
          runtime: 'go116'
          entry_point: 'GetOncall'
          project_id: ${{ env.GCP_PROJECT }}
          source_dir: ./get-oncall
          secret_environment_variables: 'SLACK_SECRET=projects/${{ env.GCP_PROJECT }}/secrets/SLACK_CLIENT_SECRET/versions/,SLACK_API_KEY=projects/${{ env.GCP_PROJECT }}/secrets/SLACK_API_KEY/versions/,PD_API_KEY=projects/${{ env.GCP_PROJECT }}/secrets/PD_API_KEY/versions/'
          memory_mb: '512'
          region: us-central1
          min_instances: 0
          max_instances: 1
          timeout: 60
          deploy_timeout: 900
