name: deploy-get-oncall

on:
  push:
    branches:
      - main
    paths:
      - "get-oncall/**"
      - ".github/workflows/deploy-function-getoncall.yaml"
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - id: auth
        uses: google-github-actions/auth@f105ef0cdb3b102a020be1767fcc8a974898b7c6 # v1.2.0
        with:
          workload_identity_provider: "projects/801815070094/locations/global/workloadIdentityPools/tooling-pool/providers/github-actions-provider"
          service_account: "github-actions@sigstore-support-tooling.iam.gserviceaccount.com"

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@4f9427c63ffe3ceeae0032efc3ebeb686417c1cf # v1.0.1
        with:
          name: 'GetOncall'
          runtime: 'go116'
          entry_point: 'GetOncall'
          project_id: ${{ env.GCP_PROJECT }}
          source_dir: ./get-oncall
          secret_environment_variables: 'SLACK_SECRET=projects/${{ env.GCP_PROJECT }}/secrets/SLACK_CLIENT_SECRET/versions/,SLACK_API_KEY=projects/${{ env.GCP_PROJECT }}/secrets/SLACK_API_KEY/versions/,PD_API_KEY=projects/${{ env.GCP_PROJECT }}/secrets/PD_API_KEY/versions/'
          memory_mb: '512'
          region: us-central1
          min_instances: 0
          max_instances: 1
          timeout: 60
          deploy_timeout: 900
